language: minimal

dist: bionic

before_install:
  # Download the Microsoft repository GPG keys
  - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
  # Register the Microsoft repository GPG keys
  - sudo dpkg -i packages-microsoft-prod.deb
  # Update the list of products
  - sudo apt-get update
  # Enable the "universe" repositories
  - sudo add-apt-repository universe
  # Install PowerShell
  - sudo apt-get install -y powershell

script:
  - pwsh -c 'Import-Module ./PSSourcegraph/PSSourcegraph.psd1'

if: tag IS blank

jobs:
  include:
    - stage: test
    - stage: release
      cache:
        yarn: true
      install:
        - yarn --frozen-lockfile
      script:
        - yarn semantic-release

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false
